### YamlMime:ManagedReference
items:
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule
  commentId: T:Gasimo.CineBlend.Modules.CineRecomposeModule
  id: CineRecomposeModule
  parent: Gasimo.CineBlend.Modules
  children:
  - Gasimo.CineBlend.Modules.CineRecomposeModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
  - Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize(Gasimo.CineBlend.VirtualCamera)
  - Gasimo.CineBlend.Modules.CineRecomposeModule.PositionOffset
  - Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
  - Gasimo.CineBlend.Modules.CineRecomposeModule.RotationOffset
  langs:
  - csharp
  - vb
  name: CineRecomposeModule
  nameWithType: CineRecomposeModule
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule
  type: Class
  source:
    id: CineRecomposeModule
    path: E:\Projects\antartica-project\Plugins\CineBlend\Source\Cineblend\Runtime\Modules\CineRecomposeModule.cs
    startLine: 9
  assemblies:
  - Cineblend.CSharp
  namespace: Gasimo.CineBlend.Modules
  summary: Allows you to offset the position and rotation of the camera.
  example: []
  syntax:
    content: >-
      [RequireActor(typeof(VirtualCamera))]

      [Category("Cineblend")]

      public class CineRecomposeModule : Script, ICameraModule
    content.vb: >-
      <RequireActor(GetType(VirtualCamera))>

      <Category("Cineblend")>

      Public Class CineRecomposeModule Inherits Script Implements ICameraModule
  inheritance:
  - System.Object
  - FlaxEngine.Object
  - FlaxEngine.SceneObject
  - FlaxEngine.Script
  implements:
  - Gasimo.CineBlend.ICameraModule
  attributes:
  - type: FlaxEngine.RequireActorAttribute
    ctor: FlaxEngine.RequireActorAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Gasimo.CineBlend.VirtualCamera
  - type: FlaxEngine.CategoryAttribute
    ctor: FlaxEngine.CategoryAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Cineblend
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.PositionOffset
  commentId: F:Gasimo.CineBlend.Modules.CineRecomposeModule.PositionOffset
  id: PositionOffset
  parent: Gasimo.CineBlend.Modules.CineRecomposeModule
  langs:
  - csharp
  - vb
  name: PositionOffset
  nameWithType: CineRecomposeModule.PositionOffset
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.PositionOffset
  type: Field
  source:
    id: PositionOffset
    path: E:\Projects\antartica-project\Plugins\CineBlend\Source\Cineblend\Runtime\Modules\CineRecomposeModule.cs
    startLine: 14
  assemblies:
  - Cineblend.CSharp
  namespace: Gasimo.CineBlend.Modules
  syntax:
    content: public Vector3 PositionOffset
    return:
      type: FlaxEngine.Vector3
    content.vb: Public PositionOffset As Vector3
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.RotationOffset
  commentId: F:Gasimo.CineBlend.Modules.CineRecomposeModule.RotationOffset
  id: RotationOffset
  parent: Gasimo.CineBlend.Modules.CineRecomposeModule
  langs:
  - csharp
  - vb
  name: RotationOffset
  nameWithType: CineRecomposeModule.RotationOffset
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.RotationOffset
  type: Field
  source:
    id: RotationOffset
    path: E:\Projects\antartica-project\Plugins\CineBlend\Source\Cineblend\Runtime\Modules\CineRecomposeModule.cs
    startLine: 15
  assemblies:
  - Cineblend.CSharp
  namespace: Gasimo.CineBlend.Modules
  syntax:
    content: public Quaternion RotationOffset
    return:
      type: FlaxEngine.Quaternion
    content.vb: Public RotationOffset As Quaternion
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
  commentId: M:Gasimo.CineBlend.Modules.CineRecomposeModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
  id: Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
  parent: Gasimo.CineBlend.Modules.CineRecomposeModule
  langs:
  - csharp
  - vb
  name: Blend(VirtualCamera, VirtualCamera, float)
  nameWithType: CineRecomposeModule.Blend(VirtualCamera, VirtualCamera, float)
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.Blend(Gasimo.CineBlend.VirtualCamera, Gasimo.CineBlend.VirtualCamera, float)
  type: Method
  source:
    id: Blend
    path: E:\Projects\antartica-project\Plugins\CineBlend\Source\Cineblend\Runtime\Modules\CineRecomposeModule.cs
    startLine: 18
  assemblies:
  - Cineblend.CSharp
  namespace: Gasimo.CineBlend.Modules
  summary: Blends between two module states
  example: []
  syntax:
    content: public void Blend(VirtualCamera fromSnapshot, VirtualCamera toSnapshot, float t)
    parameters:
    - id: fromSnapshot
      type: Gasimo.CineBlend.VirtualCamera
    - id: toSnapshot
      type: Gasimo.CineBlend.VirtualCamera
    - id: t
      type: System.Single
    content.vb: Public Sub Blend(fromSnapshot As VirtualCamera, toSnapshot As VirtualCamera, t As Single)
  overload: Gasimo.CineBlend.Modules.CineRecomposeModule.Blend*
  implements:
  - Gasimo.CineBlend.ICameraModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
  nameWithType.vb: CineRecomposeModule.Blend(VirtualCamera, VirtualCamera, Single)
  fullName.vb: Gasimo.CineBlend.Modules.CineRecomposeModule.Blend(Gasimo.CineBlend.VirtualCamera, Gasimo.CineBlend.VirtualCamera, Single)
  name.vb: Blend(VirtualCamera, VirtualCamera, Single)
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize(Gasimo.CineBlend.VirtualCamera)
  commentId: M:Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize(Gasimo.CineBlend.VirtualCamera)
  id: Initialize(Gasimo.CineBlend.VirtualCamera)
  parent: Gasimo.CineBlend.Modules.CineRecomposeModule
  langs:
  - csharp
  - vb
  name: Initialize(VirtualCamera)
  nameWithType: CineRecomposeModule.Initialize(VirtualCamera)
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize(Gasimo.CineBlend.VirtualCamera)
  type: Method
  source:
    id: Initialize
    path: E:\Projects\antartica-project\Plugins\CineBlend\Source\Cineblend\Runtime\Modules\CineRecomposeModule.cs
    startLine: 23
  assemblies:
  - Cineblend.CSharp
  namespace: Gasimo.CineBlend.Modules
  summary: Called when the module is initialized
  example: []
  syntax:
    content: public void Initialize(VirtualCamera camera)
    parameters:
    - id: camera
      type: Gasimo.CineBlend.VirtualCamera
    content.vb: Public Sub Initialize(camera As VirtualCamera)
  overload: Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize*
  implements:
  - Gasimo.CineBlend.ICameraModule.Initialize(Gasimo.CineBlend.VirtualCamera)
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
  commentId: M:Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
  id: PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
  parent: Gasimo.CineBlend.Modules.CineRecomposeModule
  langs:
  - csharp
  - vb
  name: PostProcessProperties(ref CameraProperties)
  nameWithType: CineRecomposeModule.PostProcessProperties(ref CameraProperties)
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties(ref Gasimo.CineBlend.CameraProperties)
  type: Method
  source:
    id: PostProcessProperties
    path: E:\Projects\antartica-project\Plugins\CineBlend\Source\Cineblend\Runtime\Modules\CineRecomposeModule.cs
    startLine: 28
  assemblies:
  - Cineblend.CSharp
  namespace: Gasimo.CineBlend.Modules
  summary: Modifies the final camera properties before they are applied
  example: []
  syntax:
    content: public void PostProcessProperties(ref CameraProperties state)
    parameters:
    - id: state
      type: Gasimo.CineBlend.CameraProperties
    content.vb: Public Sub PostProcessProperties(state As CameraProperties)
  overload: Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties*
  implements:
  - Gasimo.CineBlend.ICameraModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
  nameWithType.vb: CineRecomposeModule.PostProcessProperties(CameraProperties)
  fullName.vb: Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties)
  name.vb: PostProcessProperties(CameraProperties)
references:
- uid: Gasimo.CineBlend.Modules
  commentId: N:Gasimo.CineBlend.Modules
  href: Gasimo.html
  name: Gasimo.CineBlend.Modules
  nameWithType: Gasimo.CineBlend.Modules
  fullName: Gasimo.CineBlend.Modules
  spec.csharp:
  - uid: Gasimo
    name: Gasimo
    href: Gasimo.html
  - name: .
  - uid: Gasimo.CineBlend
    name: CineBlend
    href: Gasimo.CineBlend.html
  - name: .
  - uid: Gasimo.CineBlend.Modules
    name: Modules
    href: Gasimo.CineBlend.Modules.html
  spec.vb:
  - uid: Gasimo
    name: Gasimo
    href: Gasimo.html
  - name: .
  - uid: Gasimo.CineBlend
    name: CineBlend
    href: Gasimo.CineBlend.html
  - name: .
  - uid: Gasimo.CineBlend.Modules
    name: Modules
    href: Gasimo.CineBlend.Modules.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: FlaxEngine.Object
  commentId: T:FlaxEngine.Object
  parent: FlaxEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: FlaxEngine.Object
- uid: FlaxEngine.SceneObject
  commentId: T:FlaxEngine.SceneObject
  parent: FlaxEngine
  isExternal: true
  name: SceneObject
  nameWithType: SceneObject
  fullName: FlaxEngine.SceneObject
- uid: FlaxEngine.Script
  commentId: T:FlaxEngine.Script
  parent: FlaxEngine
  isExternal: true
  name: Script
  nameWithType: Script
  fullName: FlaxEngine.Script
- uid: Gasimo.CineBlend.ICameraModule
  commentId: T:Gasimo.CineBlend.ICameraModule
  parent: Gasimo.CineBlend
  href: Gasimo.CineBlend.ICameraModule.html
  name: ICameraModule
  nameWithType: ICameraModule
  fullName: Gasimo.CineBlend.ICameraModule
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: FlaxEngine
  commentId: N:FlaxEngine
  isExternal: true
  name: FlaxEngine
  nameWithType: FlaxEngine
  fullName: FlaxEngine
- uid: Gasimo.CineBlend
  commentId: N:Gasimo.CineBlend
  href: Gasimo.html
  name: Gasimo.CineBlend
  nameWithType: Gasimo.CineBlend
  fullName: Gasimo.CineBlend
  spec.csharp:
  - uid: Gasimo
    name: Gasimo
    href: Gasimo.html
  - name: .
  - uid: Gasimo.CineBlend
    name: CineBlend
    href: Gasimo.CineBlend.html
  spec.vb:
  - uid: Gasimo
    name: Gasimo
    href: Gasimo.html
  - name: .
  - uid: Gasimo.CineBlend
    name: CineBlend
    href: Gasimo.CineBlend.html
- uid: FlaxEngine.Vector3
  commentId: T:FlaxEngine.Vector3
  parent: FlaxEngine
  isExternal: true
  name: Vector3
  nameWithType: Vector3
  fullName: FlaxEngine.Vector3
- uid: FlaxEngine.Quaternion
  commentId: T:FlaxEngine.Quaternion
  parent: FlaxEngine
  isExternal: true
  name: Quaternion
  nameWithType: Quaternion
  fullName: FlaxEngine.Quaternion
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.Blend*
  commentId: Overload:Gasimo.CineBlend.Modules.CineRecomposeModule.Blend
  href: Gasimo.CineBlend.Modules.CineRecomposeModule.html#Gasimo_CineBlend_Modules_CineRecomposeModule_Blend_Gasimo_CineBlend_VirtualCamera_Gasimo_CineBlend_VirtualCamera_System_Single_
  name: Blend
  nameWithType: CineRecomposeModule.Blend
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.Blend
- uid: Gasimo.CineBlend.ICameraModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
  commentId: M:Gasimo.CineBlend.ICameraModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
  parent: Gasimo.CineBlend.ICameraModule
  isExternal: true
  href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_Blend_Gasimo_CineBlend_VirtualCamera_Gasimo_CineBlend_VirtualCamera_System_Single_
  name: Blend(VirtualCamera, VirtualCamera, float)
  nameWithType: ICameraModule.Blend(VirtualCamera, VirtualCamera, float)
  fullName: Gasimo.CineBlend.ICameraModule.Blend(Gasimo.CineBlend.VirtualCamera, Gasimo.CineBlend.VirtualCamera, float)
  nameWithType.vb: ICameraModule.Blend(VirtualCamera, VirtualCamera, Single)
  fullName.vb: Gasimo.CineBlend.ICameraModule.Blend(Gasimo.CineBlend.VirtualCamera, Gasimo.CineBlend.VirtualCamera, Single)
  name.vb: Blend(VirtualCamera, VirtualCamera, Single)
  spec.csharp:
  - uid: Gasimo.CineBlend.ICameraModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
    name: Blend
    href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_Blend_Gasimo_CineBlend_VirtualCamera_Gasimo_CineBlend_VirtualCamera_System_Single_
  - name: (
  - uid: Gasimo.CineBlend.VirtualCamera
    name: VirtualCamera
    href: Gasimo.CineBlend.VirtualCamera.html
  - name: ','
  - name: " "
  - uid: Gasimo.CineBlend.VirtualCamera
    name: VirtualCamera
    href: Gasimo.CineBlend.VirtualCamera.html
  - name: ','
  - name: " "
  - uid: System.Single
    name: float
    isExternal: true
  - name: )
  spec.vb:
  - uid: Gasimo.CineBlend.ICameraModule.Blend(Gasimo.CineBlend.VirtualCamera,Gasimo.CineBlend.VirtualCamera,System.Single)
    name: Blend
    href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_Blend_Gasimo_CineBlend_VirtualCamera_Gasimo_CineBlend_VirtualCamera_System_Single_
  - name: (
  - uid: Gasimo.CineBlend.VirtualCamera
    name: VirtualCamera
    href: Gasimo.CineBlend.VirtualCamera.html
  - name: ','
  - name: " "
  - uid: Gasimo.CineBlend.VirtualCamera
    name: VirtualCamera
    href: Gasimo.CineBlend.VirtualCamera.html
  - name: ','
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
  - name: )
- uid: Gasimo.CineBlend.VirtualCamera
  commentId: T:Gasimo.CineBlend.VirtualCamera
  parent: Gasimo.CineBlend
  href: Gasimo.CineBlend.VirtualCamera.html
  name: VirtualCamera
  nameWithType: VirtualCamera
  fullName: Gasimo.CineBlend.VirtualCamera
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize*
  commentId: Overload:Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize
  href: Gasimo.CineBlend.Modules.CineRecomposeModule.html#Gasimo_CineBlend_Modules_CineRecomposeModule_Initialize_Gasimo_CineBlend_VirtualCamera_
  name: Initialize
  nameWithType: CineRecomposeModule.Initialize
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.Initialize
- uid: Gasimo.CineBlend.ICameraModule.Initialize(Gasimo.CineBlend.VirtualCamera)
  commentId: M:Gasimo.CineBlend.ICameraModule.Initialize(Gasimo.CineBlend.VirtualCamera)
  parent: Gasimo.CineBlend.ICameraModule
  href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_Initialize_Gasimo_CineBlend_VirtualCamera_
  name: Initialize(VirtualCamera)
  nameWithType: ICameraModule.Initialize(VirtualCamera)
  fullName: Gasimo.CineBlend.ICameraModule.Initialize(Gasimo.CineBlend.VirtualCamera)
  spec.csharp:
  - uid: Gasimo.CineBlend.ICameraModule.Initialize(Gasimo.CineBlend.VirtualCamera)
    name: Initialize
    href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_Initialize_Gasimo_CineBlend_VirtualCamera_
  - name: (
  - uid: Gasimo.CineBlend.VirtualCamera
    name: VirtualCamera
    href: Gasimo.CineBlend.VirtualCamera.html
  - name: )
  spec.vb:
  - uid: Gasimo.CineBlend.ICameraModule.Initialize(Gasimo.CineBlend.VirtualCamera)
    name: Initialize
    href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_Initialize_Gasimo_CineBlend_VirtualCamera_
  - name: (
  - uid: Gasimo.CineBlend.VirtualCamera
    name: VirtualCamera
    href: Gasimo.CineBlend.VirtualCamera.html
  - name: )
- uid: Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties*
  commentId: Overload:Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties
  href: Gasimo.CineBlend.Modules.CineRecomposeModule.html#Gasimo_CineBlend_Modules_CineRecomposeModule_PostProcessProperties_Gasimo_CineBlend_CameraProperties__
  name: PostProcessProperties
  nameWithType: CineRecomposeModule.PostProcessProperties
  fullName: Gasimo.CineBlend.Modules.CineRecomposeModule.PostProcessProperties
- uid: Gasimo.CineBlend.ICameraModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
  commentId: M:Gasimo.CineBlend.ICameraModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
  parent: Gasimo.CineBlend.ICameraModule
  href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_PostProcessProperties_Gasimo_CineBlend_CameraProperties__
  name: PostProcessProperties(ref CameraProperties)
  nameWithType: ICameraModule.PostProcessProperties(ref CameraProperties)
  fullName: Gasimo.CineBlend.ICameraModule.PostProcessProperties(ref Gasimo.CineBlend.CameraProperties)
  nameWithType.vb: ICameraModule.PostProcessProperties(CameraProperties)
  fullName.vb: Gasimo.CineBlend.ICameraModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties)
  name.vb: PostProcessProperties(CameraProperties)
  spec.csharp:
  - uid: Gasimo.CineBlend.ICameraModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
    name: PostProcessProperties
    href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_PostProcessProperties_Gasimo_CineBlend_CameraProperties__
  - name: (
  - name: ref
  - name: " "
  - uid: Gasimo.CineBlend.CameraProperties
    name: CameraProperties
    href: Gasimo.CineBlend.CameraProperties.html
  - name: )
  spec.vb:
  - uid: Gasimo.CineBlend.ICameraModule.PostProcessProperties(Gasimo.CineBlend.CameraProperties@)
    name: PostProcessProperties
    href: Gasimo.CineBlend.ICameraModule.html#Gasimo_CineBlend_ICameraModule_PostProcessProperties_Gasimo_CineBlend_CameraProperties__
  - name: (
  - uid: Gasimo.CineBlend.CameraProperties
    name: CameraProperties
    href: Gasimo.CineBlend.CameraProperties.html
  - name: )
- uid: Gasimo.CineBlend.CameraProperties
  commentId: T:Gasimo.CineBlend.CameraProperties
  parent: Gasimo.CineBlend
  href: Gasimo.CineBlend.CameraProperties.html
  name: CameraProperties
  nameWithType: CameraProperties
  fullName: Gasimo.CineBlend.CameraProperties
